const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../assets/maritime-ai.js'),'utf8');
function setup(handler){const calls=[];const scope={AbortController,Date,TypeError,setTimeout:(f,ms)=>ms===30000?setTimeout(f,ms):setTimeout(f,0),clearTimeout,fetch:async(url,options)=>{calls.push([url,options]);return handler(url,options,calls);}};vm.createContext(scope);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../assets/ai-dialogue-policy.js'),'utf8'),scope);vm.runInContext(source,scope);return {ai:scope.MaritimeAI,calls};}
const res=(data,status=200)=>({ok:status<400,status,headers:{get:()=>null},json:async()=>data});const catalog={data:[{id:'paid-model',model_type:'chat',tier:'pro',usage_based_only:true},{id:'codestral-latest',model_type:'chat',tier:'turbo',usage_based_only:false},{id:'backup',model_type:'chat',tier:'turbo',usage_based_only:false}]};
const opts={system:'Educational role',messages:[{role:'user',content:'Please confirm ETA'}]};
test('uses anonymous eligible catalog, preserves generated response and model',async()=>{const {ai,calls}=setup(url=>res(url.endsWith('/models')?catalog:{model:'codestral-latest',choices:[{message:{content:'ETA needs confirmation.'}}]}));const r=await ai.reply(opts);assert.equal(r.text,'ETA needs confirmation.');assert.equal(JSON.parse(calls[1][1].body).model,'codestral-latest');assert.equal(calls[1][1].headers.Authorization,undefined);});
test('unavailable model falls back; never selects paid entries',async()=>{let count=0;const {ai}=setup(url=>url.endsWith('/models')?res(catalog):++count===1?res({error:{code:'model_unavailable'}},400):res({model:'backup',choices:[{message:{content:'Reply'}}]}));assert.equal((await ai.reply(opts)).model,'backup');});
test('rate limit retries only once and releases queue after failure',async()=>{let count=0;const {ai}=setup(url=>url.endsWith('/models')?res(catalog):++count<=2?res({error:{retry_after:2}},429):res({choices:[{message:{content:'Recovered'}}]}));await assert.rejects(ai.reply(opts),/busy/);assert.equal((await ai.reply(opts)).text,'Recovered');});
test('empty generation is an error, never an invented officer reply',async()=>{const {ai}=setup(url=>res(url.endsWith('/models')?catalog:{choices:[{message:{content:''}}]}));await assert.rejects(ai.reply(opts),/empty response/);});
test('no eligible models does not silently use a paid tier',async()=>{const {ai,calls}=setup(()=>res({data:[catalog.data[0]]}));await assert.rejects(ai.reply(opts),/No anonymous/);assert.equal(calls.length,1);});
test('two calls are serialized',async()=>{let concurrent=0,max=0;const {ai}=setup(async url=>{if(url.endsWith('/models'))return res(catalog);concurrent++;max=Math.max(max,concurrent);await new Promise(r=>setTimeout(r,10));concurrent--;return res({choices:[{message:{content:'Done'}}]});});await Promise.all([ai.reply(opts),ai.reply(opts)]);assert.equal(max,1);});

test('conversation instructions and earlier context reach the model',async()=>{const {ai,calls}=setup(url=>res(url.endsWith('/models')?catalog:{choices:[{message:{content:'Explanation'}}]}));const messages=Array.from({length:18},(_,i)=>({role:i%2?'assistant':'user',content:'Turn '+i}));await ai.reply({...opts,messages});const body=JSON.parse(calls[1][1].body);assert.equal(body.messages[1].content,'Turn 0');assert.match(body.messages[0].content,/Do not append a question automatically/);assert.match(body.messages[0].content,/General|general language/);assert.ok(body.max_tokens>=1000);});
