const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../itm2-missions/operations/missions.js');const C=require('../itm2-missions/operations/core.js');
for(const m of Object.values(M)){
test(m.id+' eight-phase workflow, sources, export and revision',()=>{const s=C.fresh(m.id);assert.equal(m.stages.length,8);for(let i=0;i<8;i++){s.stage=i;const t=m.stages[i];assert.ok(C.validate(m,s).length);for(const id of t.docs){assert.ok(C.available(m,s).some(d=>d.id===id),'source must be released: '+id);s.read[id]='test';}for(const f of t.fields){if(f.expected)assert.ok(f.type==='map'||f.options.some(o=>o.value===f.expected));C.edit(m,s,f.id,f.expected||'Original learner response for workflow testing. '.repeat(Math.ceil(f.min/40)));}assert.equal(C.commit(m,s).ok,true);assert.equal(s.done.length,i+1);}assert.equal(C.packet(m,s).completionStatus,'complete');assert.equal(C.packet(m,s).score,0);assert.equal(C.packet(m,s).workflowCompletion,100);s.stage=2;C.edit(m,s,m.stages[2].fields[0].id,'Revised');assert.equal(s.done.length,2);assert.equal(s.completionStatus,'partial');assert.ok(s.answers[m.stages[7].id]);assert.equal(C.packet(m,s).completedAt,null);});
test(m.id+' wrong evidence decision blocks advancement and records attempt',()=>{const s=C.fresh(m.id),t=m.stages[0];t.docs.forEach(id=>s.read[id]=true);for(const f of t.fields)C.edit(m,s,f.id,f.expected||'Response '.repeat(f.min));const selected=t.fields.find(f=>f.expected);C.edit(m,s,selected.id,'unsupported');assert.equal(C.commit(m,s).ok,false);assert.equal(s.done.length,0);assert.equal(s.attempts.length,1);assert.ok(!C.available(m,s).some(d=>d.available>0));});}
test('historical outcome and later findings are released after pre-outcome message',()=>{const m=M.m3;assert.ok(m.documents.find(d=>d.id==='events').available>m.stages.findIndex(t=>t.id==='radio'));assert.ok(m.documents.find(d=>d.id==='findings').available>m.stages.findIndex(t=>t.id==='radio'));});
const AI=require('../itm2-missions/operations/ai-context.js');
test('AI receives actual prose, stage-specific sources and explicit language',()=>{const s=C.fresh('m2');s.answers.triage={'pilot':'Minute value unconfirmed','triage-note':'My actual draft.'};const prompt=AI.build(M.m2,s,'review','Spanish');assert.match(prompt,/My actual draft/);assert.match(prompt,/UNKNOWN/);assert.doesNotMatch(prompt,/1515 UTC/);assert.doesNotMatch(prompt,/11:57/);assert.match(prompt,/Explain in Spanish/);assert.match(prompt,/NOT as the operational recipient/);});
test('known unconfirmed-time hallucination is withheld',()=>{const s=C.fresh('m2');assert.ok(AI.audit('The revised pilot boarding time is 1500 UTC.',M.m2,s,'English'));assert.equal(AI.audit('The original 1500 is outdated. Please clarify the missing minute.',M.m2,s,'English'),'');assert.equal(AI.language('Explícalo en español','English'),'Spanish');});

const Guide=require('../itm2-missions/operations/guide.js');
test('all 24 phases have a three-action guide and output checklist',()=>{for(const m of Object.values(M)){assert.equal(Guide[m.id].length,m.stages.length);for(const g of Guide[m.id]){assert.equal(g.slice(2,5).length,3);assert.ok(g.slice(0,5).every(x=>typeof x==='string'&&x.length>15));assert.ok(g[5].length>=2);}}});
test('review contains only the selected written task; roleplay uses its actual recipient',()=>{const s=C.fresh('m2');s.stage=3;s.answers.instructions={'permit-order':'Do not admit the contractor until the signed permit is checked.','deck-order':'AB, secure the hatch lashings and report back.'};const review=AI.build(M.m2,s,'review','Spanish','permit-order');assert.match(review,/Do not admit/);assert.doesNotMatch(review,/AB, secure/);const role=AI.build(M.m2,s,'rehearse','Spanish','deck-order');assert.match(role,/Simulated recipient: AB/);assert.match(role,/Reply as the recipient in English/);assert.equal(AI.canRehearse('reflection'),false);assert.equal(AI.canRehearse('deck-order'),true);});
