(function(){
'use strict';
const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),m=OperationsMissions[q.get('mission')]||OperationsMissions.m2,C=OperationsCore;
const key='maresp_operations_v2_'+(q.get('participant')||'local')+'_'+m.id+(q.get('preview')==='1'?'_preview':'');
let s=C.fresh(m.id),run=0,busy=false,viewKey="";try{const old=JSON.parse(localStorage.getItem(key));if(old?.version===2&&old.mission===m.id&&old.stage>=0&&old.stage<m.stages.length)s=old;}catch(e){}
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function publish(){if(parent!==window)parent.postMessage({type:'maresp-mission-result',missionId:'itm2_live_'+m.id,result:C.packet(m,s)},location.origin);}
function save(){s.updatedAt=new Date().toISOString();try{localStorage.setItem(key,JSON.stringify(s));$('save-status').textContent='Saved on this device';}catch(e){$('save-status').textContent='Storage unavailable — export your record';}}
function exportRecord(format='json'){const packet=C.packet(m,s);packet.participant=q.get('participant')||'local';let body=JSON.stringify(packet,null,2),type='application/json';if(format==='md'){body=['# '+m.title,'Status: '+s.completionStatus+' · Workflow: '+s.done.length+'/8','Participant: '+packet.participant,m.basis,'## Sources',...m.sourceNotes.map(x=>'- '+x),'## Student communications',...m.stages.flatMap(t=>['### '+t.title,'Recipient / record: '+t.delivery,...t.fields.map(f=>'**'+f.label+'**\n\n'+(s.answers[t.id]?.[f.id]||'[Not submitted]'))]),'## Decision trail',...s.log.map(x=>'- '+x.time+' · '+x.text),'## AI rehearsal (not instructor assessment)',...s.messages.map(x=>'### '+x.stage+' · '+x.role+'\n\n'+x.content),'## Interpretation','Workflow completion checks required sources, required selections and minimum response completeness. It is not an automated language or competence grade. Drafts require instructor review.'].join('\n\n');type='text/markdown';}const a=el('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=m.id+'-mission-record.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

function feedback(){const done=s.done.includes(m.stages[s.stage].id);$('submit').disabled=done;$('outcome').textContent=done?m.stages[s.stage].consequence:'';$('continue').hidden=!done||s.stage===m.stages.length-1;$('finish').hidden=s.completionStatus!=='complete';$('progress-label').textContent=s.done.length+' / '+m.stages.length;$('progress-bar').style.width=(100*s.done.length/m.stages.length)+'%';$('trace').replaceChildren(...s.log.slice(-8).map(x=>el('p',x.text)));}
function richText(text){const box=el('div');for(const line of text.split('\n').filter(x=>x.trim())){const p=el('p');for(const [i,part] of line.split(/\*\*(.*?)\*\*/g).entries())p.append(i%2?el('strong',part):document.createTextNode(part));box.append(p);}return box;}
function chat(){const list=s.messages.filter(x=>x.stage===m.stages[s.stage].id);$('ai-log').replaceChildren(...list.map(x=>{const n=el('div',undefined,'chat-message '+x.role);n.append(el('strong',x.role==='user'?'You':x.mode==='rehearse'?m.stages[s.stage].aiRole:'Communication tutor'),richText(x.content));if(x.model)n.append(el('small',x.model));return n;}));$('ai-log').scrollTop=$('ai-log').scrollHeight;}
function render(){const changed=viewKey!==s.createdAt+':'+s.stage;if(changed){viewKey=s.createdAt+':'+s.stage;run++;busy=false;$('ai-send').disabled=false;$('ai-status').textContent='Optional rehearsal — your submitted communication is recorded in the main panel.';$('ai-input').value='';}const t=m.stages[s.stage];document.title=m.title+' · MAR-ESP';$('mission-no').textContent='MISSION '+m.number;$('mission-title').textContent=m.title;$('mission-subtitle').textContent=m.subtitle;$('assignment').textContent=m.role+' · '+m.ship;$('mission-meta').textContent=m.duration+' · '+m.clock;$('phase-title').textContent=t.title;$('phase-time').textContent=t.time;$('phase-kind').textContent=m.kind;$('objective').textContent=t.objective;$('briefing').textContent=s.stage===0?m.intro:'';$('delivery').textContent=t.delivery;$('ai-role').textContent=t.aiRole;$('ai-purpose').textContent=t.aiTask;$('sources').replaceChildren(el('p',m.basis),...m.sourceNotes.map(x=>el('p',x)));$('errors').replaceChildren();
$('steps').replaceChildren(...m.stages.map((st,i)=>{const b=el('button',(s.done.includes(st.id)?'✓ ':'')+st.title);b.disabled=i>s.done.length;b.className=i===s.stage?'active':'';b.onclick=()=>{s.stage=i;save();render();};return b;}));
$('documents').replaceChildren(...C.available(m,s).map(d=>{const b=el('button',undefined,'source-button'+(s.read[d.id]?' read':''));b.append(el('b',d.title),el('span',s.read[d.id]?'Opened':t.docs.includes(d.id)?'Required this phase':'Available source','doc-state'));b.id='doc-'+d.id;b.onclick=()=>{$('doc-title').textContent=d.title;$('doc-ref').textContent=d.ref;$('doc-body').textContent=d.body;s.read[d.id]=new Date().toISOString();save();b.classList.add('read');b.lastChild.textContent='Opened';$('document-dialog').showModal();};return b;}));
$('visual').replaceChildren();if(m.id==='m3'&&s.stage<=3){$('visual').append(el('p',s.stage===0?'Traffic reconstruction · 0115: Kingston ahead 6.3 NM; Rickmers Dubai SOG 15.4 kn; Kingston 6 kn.':'Traffic reconstruction · 0145: range 1.6 NM; predicted CPA 40 m. A prediction is not an agreed passing arrangement.','visual-card'));}
if(m.id==='m4'&&s.stage===0){const card=el('div',undefined,'visual-card');card.innerHTML='<svg viewBox="0 0 520 280" role="img" aria-label="Deck 3 schematic, bow at top, port at left. FD-3A is port aft of the accommodation access corridor. Not to scale."><path d="M155 255 L155 65 Q260 -30 365 65 L365 255 Z" fill="#172f3b" stroke="#80d4d3" stroke-width="2"/><text x="260" y="35" text-anchor="middle" fill="#e6eef1">BOW / FORWARD</text><rect x="215" y="95" width="90" height="75" fill="#334b59"/><text x="260" y="125" text-anchor="middle" fill="#e6eef1">Accommodation</text><text x="260" y="150" text-anchor="middle" fill="#e6eef1">access corridor</text><circle cx="185" cy="198" r="12" fill="#edbc79"/><text x="25" y="204" fill="#edbc79">FD-3A →</text><text x="60" y="90" fill="#e6eef1">PORT</text><text x="390" y="90" fill="#e6eef1">STARBOARD</text><text x="260" y="241" text-anchor="middle" fill="#e6eef1">AFT · DECK 3</text></svg>';card.append(el('small','Original training schematic · fictional vessel · not to scale.'));$('visual').append(card);}
if(m.id==='m3'&&s.stage<=3){const diagram=el('div',undefined,'visual-card');diagram.innerHTML='<svg viewBox="0 0 540 125" role="img" aria-label="Relative traffic schematic. Rickmers Dubai follows Kingston and its tow. Distance decreases from 6.3 nautical miles at 0115 to 1.6 at 0145. Not a radar display."><path d="M40 55 L90 40 L90 70 Z M410 55 L450 42 L450 68 Z" fill="#80d4d3"/><rect x="145" y="44" width="40" height="22" fill="#edbc79"/><path d="M90 55 H145" stroke="#edbc79" stroke-dasharray="4 3"/><text x="25" y="100" fill="#e6eef1">Kingston</text><text x="130" y="100" fill="#edbc79">Tow</text><text x="355" y="100" fill="#e6eef1">Rickmers Dubai</text><text x="240" y="25" text-anchor="middle" fill="#e6eef1">Direction of travel ← · relative arrangement</text></svg>';diagram.append(el('small','Original explanatory schematic, not to scale. Identities and tow configuration are established in the report; this diagram is not evidence of what the OOW recognised.'));$('visual').append(diagram);}
$('fields').replaceChildren(...t.fields.map(f=>{const wrap=el('div',undefined,'field'),label=el('label',f.label);label.htmlFor='field-'+f.id;let input;if(f.type==='text'){input=el('textarea');input.rows=f.min>500?10:4;}else{input=el('select');input.append(new Option('Select from the evidence',''));const opts=f.options||[{value:'port-forward',label:'Port forward'},{value:'starboard-forward',label:'Starboard forward'},{value:'port-aft',label:'Port aft'},{value:'starboard-aft',label:'Starboard aft'}];opts.forEach(o=>input.append(new Option(o.label,o.value)));}input.id='field-'+f.id;input.value=s.answers[t.id]?.[f.id]||'';const count=el('small',f.type==='text'?input.value.trim().split(/\s+/).filter(Boolean).length+' words':'');input.addEventListener('input',()=>{const was=s.done.includes(t.id);C.edit(m,s,f.id,input.value);save();count.textContent=f.type==='text'?input.value.trim().split(/\s+/).filter(Boolean).length+' words':'';feedback();if(was){publish();$('steps').querySelectorAll('button').forEach((b,i)=>{b.disabled=i>s.done.length;});}});wrap.append(label,input,el('small',f.help||''),count);return wrap;}));
$('finish').replaceChildren(el('h2','Mission record ready'),el('p','All eight workflow phases are recorded. Written work and AI exchanges remain available for instructor review. Completion is not an automated language or professional competence grade.'),el('p',m.id==='m4'?'D3 remains open. Completion of this learning workflow does not mean vessel clearance.':''));const download=el('button','Download complete evidence packet','primary');download.onclick=()=>exportRecord();$('finish').append(download);const readable=el('button','Download readable report');readable.onclick=()=>exportRecord('md');$('finish').append(readable);const review=el('details');review.append(el('summary','Review all recorded communications'));m.stages.forEach(st=>{review.append(el('h3',st.title));st.fields.forEach(f=>{review.append(el('strong',f.label),el('p',s.answers[st.id]?.[f.id]||'[Not submitted]'));});});$('finish').append(review);feedback();chat();}
$('submit').onclick=()=>{const result=C.commit(m,s);save();$('errors').replaceChildren(...result.errors.map(e=>el('p',e.message)));if(!result.ok)$('errors').focus();else{publish();render();}};
$('continue').onclick=()=>{if(!s.done.includes(m.stages[s.stage].id))return;s.stage++;save();render();$('workspace').scrollIntoView({behavior:'smooth'});};
$('download-top').onclick=()=>exportRecord();$('back').onclick=e=>{if(parent!==window){e.preventDefault();parent.postMessage({type:'maresp-close-mission'},location.origin);}};
$('restart').onclick=()=>$('restart-dialog').showModal();$('cancel-restart').onclick=()=>$('restart-dialog').close();$('confirm-restart').onclick=()=>{try{localStorage.setItem(key+'_archive_'+Date.now(),JSON.stringify(s));}catch(e){$('save-status').textContent='Archive unavailable. Export before starting again.';$('restart-dialog').close();return;}s=C.fresh(m.id);save();publish();$('restart-dialog').close();render();};
$('ai-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const t=m.stages[s.stage],mode=$('ai-mode').value,draft=s.answers[t.id]||{},message=$('ai-input').value.trim();if(!message&&mode!=='review'){$('ai-status').textContent='Write the message or question you want to rehearse.';return;}if(mode==='review'&&!Object.values(draft).some(v=>String(v).trim())){$('ai-status').textContent='Write a draft in this phase before requesting a review.';return;}const token=run;busy=true;$('ai-send').disabled=true;const content=message||'Review my current draft against the released sources.';s.messages.push({stage:t.id,mode,role:'user',content,time:new Date().toISOString()});save();chat();$('ai-input').value='';
try{const lang=OperationsAIContext.language(content,$('ai-language').value),system=OperationsAIContext.build(m,s,mode,lang);let reply,answer;const conversation=s.messages.filter(x=>x.stage===t.id).slice(-12).map(x=>({role:x.role,content:x.content}));for(let attempt=0;attempt<2;attempt++){reply=await MaritimeAI.reply({system,messages:conversation,onStatus:x=>{if(token===run)$('ai-status').textContent=typeof x==='string'?x:'Connecting…';}});if(token!==run)return;answer=typeof reply==='string'?reply:reply.text||reply.content;const issue=OperationsAIContext.audit(answer||'',m,s,lang);if(!issue)break;s.rejectedAI=s.rejectedAI||[];s.rejectedAI.push({stage:t.id,content:answer,reason:issue,time:new Date().toISOString()});save();if(attempt===1)throw Error('Response withheld: '+issue);$('ai-status').textContent='Checking a source/language mismatch; requesting a corrected response…';conversation.push({role:'assistant',content:answer},{role:'user',content:'Correct your previous response. '+issue+' Follow the source boundary and reply in '+lang+'.'});}if(token!==run)return;if(!answer)throw Error('The provider returned no text.');s.messages.push({stage:t.id,mode,role:'assistant',content:answer,model:reply.model||'',time:new Date().toISOString()});save();publish();chat();$('ai-status').textContent='Rehearsal saved. Revise and submit your own communication in the main panel.';}catch(error){if(token===run)$('ai-status').textContent='AI connection failed: '+error.message+' Your draft is saved. You can continue the mission or retry.';}finally{if(token===run){busy=false;$('ai-send').disabled=false;}}};
render();
})();
