(function(root){
const G={
m2:[
['Aclara qué falta antes de actuar','La llamada se ha cortado. Todavía no puedes comunicar una nueva hora de embarque.','Lee la llamada y los tres registros.','Selecciona qué dato falta y qué llamada harías primero.','Escribe una nota breve en inglés con dos asuntos pendientes y por qué siguen abiertos.',['Dato confirmado frente a dato incompleto','Permiso y documentación pendientes'],'The agent call was interrupted. We still need to confirm…'],
['Confirma la hora con el agente','Ya tienes la devolución de llamada del agente. Debes comprobar que has entendido el cambio.','Lee la devolución de llamada.','Selecciona la hora de embarque y el plazo del correo: son dos horas distintas.','Escribe al agente en inglés: repite el dato, el motivo y lo que harás a continuación.',['Hora de embarque','Motivo del cambio','Plazo y siguiente acción'],'North Port Agency, this is MV Aurora. I read back…'],
['Comunica el cambio al oficial de guardia','El agente ha informado; ahora debes trasladar esa información a bordo.','Consulta la hora confirmada y la hoja de coordinación.','Selecciona quién necesita recibir el aviso.','Redacta el mensaje al OOW y una entrada breve para el registro.',['Fuente de la información','Hora nueva','Responsable y plazo del correo'],'OOW, North Port Agency has confirmed…'],
['Da dos instrucciones que se puedan ejecutar','Hay un permiso sin firmar y un aviso de trincas flojas en cubierta. Son dos tareas distintas.','Lee el permiso y el aviso de cubierta.','Decide la restricción de acceso y quién debe asegurar las trincas.','Escribe una orden al control de acceso y otra al AB. Indica quién actúa, dónde y cómo confirma el resultado.',['Actor y lugar exacto','Condición previa','Acción y comprobación posterior'],'Gangway watch, do not allow…'],
['Pide y verifica la documentación completa','Falta una página del manifiesto. Una firma por sí sola no demuestra que el documento esté completo.','Consulta el manifiesto y el plazo del agente.','Ordena las tres acciones del flujo documental.','Escribe al empleado de carga qué falta, qué copia necesitas y para cuándo.',['Página que falta','Copia completa y firmada','Plazo y acuse de recibo'],'Cargo clerk, please provide…'],
['Separa las promesas de los trabajos comprobados','Han llegado respuestas, pero algunas solo anuncian una acción futura.','Lee los mensajes de las 11:52.','Clasifica por separado el permiso, las trincas y el manifiesto.','Informa al Chief Officer de qué está confirmado y quién debe comprobar lo pendiente.',['Promesa frente a verificación','Asunto pendiente','Responsable del seguimiento'],'Chief Officer, the current status is…'],
['Presenta la situación al capitán','Ahora hay registros de las verificaciones. Tu función es informar y solicitar autorización.','Lee el paquete de las 11:57 y la hoja de coordinación.','Selecciona la acción que está dentro de tu autoridad.','Redacta cuatro frases: situación, implicación, verificaciones y decisión que solicitas al Master.',['Situación actual','Verificaciones con respaldo','Autoridad del Master'],'Master, the departure checks…'],
['Entrega el registro de coordinación','Reúne el trabajo de los pasos anteriores en un informe profesional.','Revisa tus mensajes y las confirmaciones finales.','Escribe el informe en inglés; la extensión orientativa es de 220–300 palabras.','Añade una reflexión: cita una expresión que mejoraste y explica para qué sirvió.',['Secuencia y horas','Acciones y verificaciones','Autorización que sigue correspondiendo al Master'],'Departure coordination record — MV Aurora…']
],
m3:[
['Identifica los buques y la situación inicial','Vas a reconstruir un caso real a partir de registros. Distingue lo que muestra una fuente de lo que concluyes tú.','Lee la ficha del caso y el registro de las 01:15.','Identifica la unidad remolcada y el buque de referencia.','Escribe tres hechos iniciales en inglés con sus datos y su fuente.',['Identidades correctas','Hora del registro','Hechos sin atribuir intenciones'],'At 0115, the CNIS record…'],
['Compara dos momentos del acercamiento','Dispones de un segundo registro. Debes explicar qué ha cambiado.','Lee los registros de las 01:15 y las 01:45.','Selecciona la distancia, el CPA y la tendencia que documentan.','Escribe un parte comparativo en inglés: dato, unidad, hora y fuente.',['Distancia y CPA diferenciados','Unidades','Comparación de las dos horas'],'Between 0115 and 0145…'],
['Comprueba lo que el AIS no demuestra','Una ausencia en AIS no basta para afirmar que no hay tráfico.','Lee las limitaciones de la fuente y la configuración del remolque.','Responde qué puede concluirse del AIS y del CPA informado.','Propón qué fuentes contrastarías y qué incertidumbre queda.',['Ausencia de señal frente a ausencia de buque','Remolque y distancia de paso','Comprobaciones necesarias'],'The absence of an AIS target does not establish…'],
['Redacta un mensaje de tráfico prudente','El borrador recibido afirma más de lo que los datos permiten. Todavía no has leído el desenlace.','Lee el borrador de tráfico y los registros disponibles.','Selecciona el propósito del mensaje.','Reescríbelo en inglés y añade una pregunta de aclaración. No inventes acuerdos ni intenciones.',['Hecho observado','Petición clara','Sin afirmar un paso seguro'],'Traffic information: …'],
['Ordena lo que ocurrió después','Se ha liberado la cronología del incidente. Ahora puedes describir los acontecimientos documentados.','Lee el registro de acontecimientos.','Ordena los tres hitos usando sus horas.','Escribe una nota cronológica sin convertir una sucesión de hechos en una explicación causal.',['Secuencia','Horas','Hechos frente a causas'],'At 0154…'],
['Corrige afirmaciones sin respaldo','Un informe profesional debe indicar cuándo algo es un hecho, una valoración o una conclusión no demostrada.','Contrasta las tres afirmaciones con los registros.','Clasifica cada afirmación.','Reformula la conclusión excesiva en inglés y explica qué evidencia falta.',['Tipo de afirmación','Fuente que la respalda','Grado de certeza'],'The available record shows…'],
['Atribuye las conclusiones de la investigación','Las conclusiones del MAIB se conocen después del suceso. No son observaciones de aquel momento.','Lee el extracto de conclusiones y el registro de las 01:45.','Selecciona cómo atribuir la conclusión al informe.','Compara tu mensaje previo con los hallazgos posteriores: qué podías saber y qué no.',['Autor de la conclusión','Información disponible entonces','Hallazgos posteriores'],'The MAIB investigation found…'],
['Entrega un informe basado en fuentes','Integra la reconstrucción sin mezclar datos contemporáneos con conclusiones posteriores.','Revisa la ficha, la cronología y los hallazgos.','Escribe un informe en inglés de unas 250–350 palabras.','Añade una reflexión sobre una afirmación que tuviste que limitar o atribuir.',['Cronología','Atribución de hallazgos','Límites de lo que se puede concluir'],'This report reconstructs…']
],
m4:[
['Haz que otro tripulante encuentre la puerta','“La puerta de atrás” no permite localizar un defecto con seguridad.','Consulta el plano y el registro de prueba de FD-3A.','Selecciona el sector del buque en el que está la puerta.','Escribe un aviso en inglés con cubierta, banda, referencia, identificador y fallo observado.',['Cubierta y banda','Identificador y referencia','Comportamiento observado'],'FD-3A is located…'],
['Describe el fallo sin inventar un incendio','El registro contiene un fallo de cierre, no un incendio observado.','Vuelve al resultado de la prueba.','Distingue la observación del riesgo posible.','Escribe una nota que separe explícitamente ambos elementos.',['Resultado de la prueba','Riesgo formulado con cautela','Sin afirmar un incendio'],'During the test, FD-3A…'],
['Gestiona dos incidencias de carga','Los registros no coinciden y hay un aviso de trincas. Una discrepancia documental no demuestra por sí sola un problema de estabilidad.','Lee las dos versiones del registro y el aviso de trincas.','Identifica la discrepancia y la comprobación que necesitas.','Redacta una consulta al loading officer y una orden separada al AB.',['Versiones y cantidades','Verificación que falta','Trincas: lugar, responsable y comprobación'],'Loading officer, revision A records…'],
['Emite una orden de corrección verificable','El ingeniero necesita una orden concreta y un criterio de cierre.','Consulta el defecto de la puerta y el procedimiento de seguimiento.','Completa los cinco campos de la ficha D-01.','Escribe en inglés qué debe hacerse, quién lo hará y qué prueba permitirá cerrar la incidencia.',['Localización y evidencia','Riesgo sin exagerar','Responsable, plazo y prueba'],'Item D-01: FD-3A…'],
['Revisa qué trabajos siguen abiertos','“Ajustado” y “comprobado” no significan lo mismo.','Lee las respuestas de los responsables.','Asigna un estado a D-01, D-02 y D-03.','Pide la evidencia que falta para la puerta. No cierres por una promesa.',['Trabajo comunicado','Prueba disponible','Verificación pendiente'],'Thank you for the adjustment report. Before closure…'],
['Registra la prueba de cierre','Ha llegado el resultado de una nueva prueba de la puerta.','Lee el registro de repetición de la prueba.','Comprueba si satisface el requisito de D-01.','Escribe la entrada de cierre y señala qué otro asunto sigue pendiente.',['Resultado de la prueba','Registro y testigo','Pendiente separado'],'D-01 verification: …'],
['Comunica al capitán lo que falta','Dos incidencias tienen evidencia de cierre; otra todavía no tiene toda la verificación.','Lee el paquete final y el procedimiento.','Selecciona una recomendación respaldada por esos documentos.','Redacta el parte al Master: cerrado, abierto y siguiente acción necesaria.',['D-01 y D-02','D-03 pendiente','Acción solicitada al Master'],'Master, D-01 and D-02…'],
['Entrega un relevo que conserve lo pendiente','Completar esta misión no significa declarar el buque autorizado para salir.','Revisa las fichas y las verificaciones.','Escribe en inglés un informe final de unas 250–350 palabras.','Explica una expresión que evita confundir una reparación con su verificación.',['Rastro de las tres incidencias','Evidencia de cierre','D-03 visible como pendiente'],'Inspection handover — MV Meridian…']
]};
G.fieldLabels={"triage-note": "Nota inicial: dos asuntos pendientes y por qué siguen abiertos", "readback-message": "Mensaje al agente: confirma lo entendido y la siguiente acción", "relay-message": "Aviso al oficial de guardia (OOW)", "relay-log": "Entrada breve en el registro de comunicaciones", "permit-order": "Orden al control de acceso (gangway watch)", "deck-order": "Orden al marinero de cubierta (AB)", "document-request": "Solicitud de documentación al cargo clerk", "followup": "Parte de asuntos pendientes al Chief Officer", "briefing": "Parte al Master en cuatro frases", "final-report": "Informe final en inglés", "reflection": "Reflexión: qué expresión mejoraste y por qué", "opening-facts": "Tres hechos iniciales con su fuente", "data-report": "Parte comparativo: datos, unidades, horas y fuentes", "verification-plan": "Plan de comprobación: fuentes que contrastarías", "traffic-message": "Mensaje de tráfico corregido", "clarification": "Pregunta para aclarar lo que todavía no sabes", "chronology-note": "Nota cronológica: ordena los hechos sin inventar causas", "repair-claim": "Reformula la afirmación sin respaldo", "comparison": "Compara lo que sabías entonces con los hallazgos posteriores", "location-message": "Aviso para localizar la puerta y describir el fallo", "evidence-note": "Nota: observación frente a riesgo posible", "cargo-query": "Consulta al loading officer sobre la discrepancia", "lashing-order": "Orden al AB sobre las trincas", "ticket-item": "1. Elemento y localización exacta", "ticket-evidence": "2. Evidencia: qué ocurrió, cuándo y según qué fuente", "ticket-risk": "3. Riesgo posible, sin exagerar la evidencia", "ticket-action": "4. Acción correctiva: responsable y plazo", "ticket-proof": "5. Prueba y testigo necesarios para cerrar D-01", "challenge": "Petición de la evidencia que falta", "closure-entry": "Entrada de verificación de D-01", "remaining": "Asunto que continúa pendiente", "master-brief": "Parte al Master: cerrado, abierto y siguiente acción"};
if(typeof module!=='undefined'&&module.exports)module.exports=G;else root.OperationsGuide=G;
})(globalThis);
