/* Original learning scenarios grounded in the supplied course material. Historical facts are labelled. */
(function(root){
const WEEK='WEEK 2–3 · G2154 Inglés Técnico Marítimo II';
const REPORT='MAIB report 29/2014 · Rickmers Dubai · October 2014';
const text=(id,label,min=35,help='')=>({id,type:'text',label,min,help});
const pick=(id,label,options,expected,help='')=>({id,type:'select',label,options:options.map(x=>typeof x==='string'?{value:x,label:x}:x),expected,help});
const doc=(id,title,ref,body,available=0)=>({id,title,ref,body,available});
const task=(id,title,time,objective,docs,fields,extra={})=>({id,title,time,objective,docs,fields,...extra});
const missions={
m2:{id:'m2',number:'02',title:'Departure Control',subtitle:'A message is not a completed action.',kind:'Operations desk',duration:'55–70 min',role:'Deck operations coordinator',ship:'MV Aurora · berth 3',clock:'11:35–12:05 UTC',intro:'A changed pilot boarding time, an unsigned access permit and deteriorating deck conditions reach your desk together. Obtain the missing details, allocate actions, verify returns and give the Master a traceable departure status.',basis:'Fictional training scenario based on WEEK 2–3, PDF pp. 2–22. Times, documents and named personnel are scenario data, not a real voyage.',sourceNotes:[WEEK+' · pp. 2–9: noun groups, repair and rotating calls.',WEEK+' · pp. 10–19: modal force, prerequisites and action ownership.',WEEK+' · pp. 20–22: briefing and completion checks.'],aiRole:'Port Agent / Chief Officer',aiPurpose:'Rehearse a clarification call, test whether your instruction can be acted on, and review the difference between requested and confirmed action.',documents:[
doc('call','11:35 · Interrupted agent call',WEEK+' · pp. 6–9; fictional communication','North Port Agency → deck coordinator. “Pilot boarding is now fifteen … [signal loss] … due to reduced visibility. Send email confirmation before twelve hundred. MV Aurora, berth 3.” The minute value is NOT confirmed. The recording is represented by this transcript; it is not authentic VHF audio.'),
doc('plan','Departure coordination sheet · revision A','Fictional vessel planning record','Ship: MV Aurora. Berth: 3. Original pilot boarding: 1500 UTC. Agent confirmation deadline: 1200 UTC. The Master retains departure authority. A received message is not evidence that the requested action has been completed.'),
doc('permit','ER-17 · Contractor access permit','Fictional company procedure for this exercise','Task: inspect an engine-room sensor. Chief Engineer authorisation: BLANK. Contractor: authorised visitor list entry pending at the gangway. Procedure for this scenario: do not admit the contractor until identity and the signed permit have both been verified. Presence of an escort does not substitute for authorisation.'),
doc('manifest','Cargo document control · copy A','Fictional document register','The agent requires the complete signed manifest before 1200 UTC. Copy A contains pages 1, 2, 3 and 5. The signature box is present only on page 5. Missing page 4 prevents this copy being treated as complete.'),
doc('repair','11:39 · Verified agent callback',WEEK+' · p. 7; fictional reply','North Port Agency confirms: pilot boarding time 1515 UTC; reason reduced visibility; email confirmation required before 1200 UTC. This callback changes the planning time only. It does not clear permits, documents or deck hazards.',1),
doc('deck','11:43 · Deck observation',WEEK+' · pp. 18–22; fictional observation','Cadet reports loose lashings near No. 2 hatch, starboard side. Rain started ten minutes ago; deck is wet. One AB is available. Observation: lashings look loose. The cadet has not inspected their tension and has no evidence of cargo movement.',3),
doc('returns','11:52 · Message returns','Fictional operations traffic', 'Agent: “Revised pilot boarding time acknowledged.” Chief Engineer: “I will sign ER-17 after checking the scope.” AB: “Lashings secured at 1151; awaiting OOW inspection.” Cargo clerk: “Replacement signed manifest, pages 1–5, sent to you.” Gangway: “Identity checked against authorised visitor list.”',5),
doc('verify','11:57 · Verification packet','Fictional inspection and receipt record','ER-17 signed by Chief Engineer at 1154 and checked by coordinator at 1155. Replacement manifest has pages 1–5 and the required signature; agent receipt confirmed at 1156. OOW inspected No. 2 hatch lashings at 1157 and confirmed the area secured. Gangway identity verification is recorded. These confirmations support a report to the Master; they are not the Master’s departure authorisation.',6)
],stages:[
task('triage','01 / Triage the incoming traffic','11:35 UTC','Distinguish the missing information from the constraints already established. Open the call, planning sheet, permit and manifest before classifying them.',['call','plan','permit','manifest'],[
pick('pilot','Status of revised pilot boarding time',['Confirmed at 1500','Minute value unconfirmed','Confirmed at 1515'],'Minute value unconfirmed'),pick('priority','First communication needed',['Clarify pilot boarding minute and read it back','Announce departure clearance','Wait until 1200'],'Clarify pilot boarding minute and read it back'),text('triage-note','Desk note: identify two unresolved items and why neither can be assumed complete',90)],{state:'4 unresolved communication controls',aiRole:'Port Agent',aiTask:'Help rehearse a targeted clarification of the incomplete call. The missing minute has not been released in this phase; do not invent it.',delivery:'Internal desk note',consequence:'Your clarification request is routed. The next phase releases the verified callback.'}),
task('readback','02 / Repair the call and close the loop','11:39 UTC','The callback is now available. Build a readback which preserves time, reason, recipient and deadline.',['call','repair','plan'],[
pick('readback-time','Pilot boarding time',['1500 UTC','1515 UTC','1550 UTC'],'1515 UTC'),pick('deadline','Email confirmation deadline',['Before 1200 UTC','Before 1515 UTC','After departure'],'Before 1200 UTC'),text('readback-message','To North Port Agency: write the clarification/readback and your next action',100,'Use the verified minute and separate pilot boarding time from the email deadline.')],{aiRole:'Port Agent',aiTask:'Respond as the port agent to the learner’s readback using the verified callback. Challenge confusion between pilot boarding and the email deadline. Do not claim the learner has sent the email.',delivery:'North Port Agency · written readback',consequence:'The minute value is recorded as 1515 UTC. The coordinator must now relay the change rather than merely store it.'}),
task('relay','03 / Relay the information to the right person','11:41 UTC','Convert the call into a usable operational message for the OOW and a single factual log line.',['repair','plan'],[
pick('recipient','Operational recipient',['OOW','Unlisted contractor','Cargo consignee'],'OOW'),text('relay-message','To OOW: report the change, its source and the action due before 1200',120,'Use reported information and one compact noun group, such as pilot boarding time.'),text('relay-log','Communication log: time, source, changed datum and pending action',75)],{aiRole:'OOW',aiTask:'Read the learner’s relay as the OOW. Identify an omitted source, deadline or actor; explain a language improvement if asked. Distinguish a proposed email from a sent email.',delivery:'OOW · relay + log',consequence:'The watch is informed of the revised planning time. Access and deck conditions remain separate outstanding controls.'}),
task('instructions','04 / Turn observations into instructions','11:43 UTC','Rain adds a deck report. Assign the permit and lashing actions using precise location, actor and sequence.',['permit','deck'],[
pick('access-force','Choose the meaning of the access restriction',['Entry is optional','Entry is prohibited until checks are complete','Escort alone authorises entry'],'Entry is prohibited until checks are complete'),pick('deck-owner','Assign the securing task',['AB, followed by OOW verification','Agent, with no verification','Contractor without permit'],'AB, followed by OOW verification'),text('permit-order','Instruction to gangway watch: prerequisite, prohibited action and report-back condition',100),text('deck-order','Instruction to the AB: observation, exact place, action, deadline and report-back',130,'Use before/after where appropriate. Do not describe suspected cargo movement as an observed fact.')],{aiRole:'Chief Officer',aiTask:'Act as the recipient checking whether these instructions name an actor, place, prerequisite and completion condition. Explain must not versus do not have to when asked; never mark a task complete.',delivery:'Gangway watch + AB · two action instructions',consequence:'Two instructions have been issued. Both stay open until an identifiable completion report is checked.'}),
task('sequence','05 / Control the document workflow','11:47 UTC','The agent’s deadline is approaching. Sequence the document actions and ask for the missing evidence without weakening the access restriction.',['manifest','permit','plan'],[
pick('first','First step',['Request the complete signed manifest','Forward copy A as complete','Declare all documents complete'],'Request the complete signed manifest'),pick('second','Second step',['Verify pages and signature on the replacement','Assume that sent means received','Release the contractor'],'Verify pages and signature on the replacement'),pick('third','Third step',['Send the verified copy and obtain receipt','Delete the missing-page note','Change the deadline without asking'],'Send the verified copy and obtain receipt'),text('document-request','To cargo clerk: specify the missing page, complete copy and deadline',110)],{aiRole:'Cargo clerk',aiTask:'Respond to a document request. Use only the manifest record. Make the learner distinguish a signed page from a complete signed manifest; do not supply fabricated page content.',delivery:'Cargo clerk · document request',consequence:'A replacement is requested; the next traffic batch contains acknowledgements and promises which must be classified.'}),
task('check-returns','06 / Acknowledged is not verified','11:52 UTC','Read the returns. Decide which controls remain open instead of treating every reply as completion.',['returns'],[
pick('permit-status','Chief Engineer: “I will sign…”',['Still open — promise only','Complete — future tense is enough'],'Still open — promise only'),pick('deck-status','AB: “secured; awaiting OOW inspection”',['Work reported; verification pending','All verification complete'],'Work reported; verification pending'),pick('cargo-status','Replacement sent by clerk',['Inspect replacement and obtain agent receipt','All pages and receipt automatically verified'],'Inspect replacement and obtain agent receipt'),text('followup','To Chief Officer: separate confirmed items, outstanding checks and named next actions',150)],{aiRole:'Chief Officer',aiTask:'Challenge any claim that a future action or acknowledgement is proof of completion. Give specific feedback on the student’s status report, not a generic safety lecture.',delivery:'Chief Officer · exception report',consequence:'The exceptions remain visible. The next phase provides a verification packet so closure can be based on records.'}),
task('authorisation','07 / Present the release conditions','11:57 UTC','Review the completed checks and report to the Master within your authority.',['verify','repair','plan'],[
pick('decision','Choose your action',['Request Master authorisation on the verified conditions','Personally authorise departure','State that the pilot is already aboard'],'Request Master authorisation on the verified conditions'),text('briefing','Four-sentence briefing: situation; remaining implication; verified actions; next authority/action',220,'Acknowledge 1515 UTC pilot boarding. Do not confuse completion of checks with authority to depart.')],{aiRole:'Master',aiTask:'Rehearse receiving the four-sentence briefing. Question unsupported clearance or an omitted verified condition. You cannot issue actual clearance or change this simulator state.',delivery:'Master · pre-departure briefing',consequence:'The verified readiness report is logged. The final record must preserve the sequence and the boundary of authority.'}),
task('record','08 / Compile the departure communication record','12:05 UTC','Create a final professional record from your messages and evidence, then review how your wording controlled action.',['repair','verify','returns'],[
text('final-report','Departure coordination record · suggested 220–300 words',650,'Include the revised time, document trail, restrictions, verified returns and the Master’s outstanding authority. Length is a completion check, not a language grade.'),text('reflection','Debrief: quote one wording choice you changed and explain its operational consequence',120)],{aiRole:'Chief Officer',aiTask:'Review the student’s own draft against the available sources. Identify at most three concrete revisions with reasons. Do not write or grade the whole report.',delivery:'Mission record · final submission',final:true,consequence:'Mission packet complete: communications, verification decisions and final record are ready for instructor review.'})]},
m3:{id:'m3',number:'03',title:'The Missing Target',subtitle:'A visible mark is not yet an explanation.',kind:'Evidence investigation',duration:'60–80 min',role:'Maritime evidence analyst / communication watch',ship:'Rickmers Dubai · Kingston · Walcon Wizard',clock:'11 January 2014 · UTC',intro:'Reconstruct a developing encounter from dated source extracts. Compare CNIS information, radar and AIS limitations, repair a traffic message and separate what could be known at the time from the investigation’s later findings.',basis:'Historical facts are paraphrased from MAIB report 29/2014. Your messages and decisions are training reconstructions, not an authentic transcript or a simulation of ship manoeuvring.',sourceNotes:[REPORT+' · PDF p. 14 / printed p. 6: 0115 and 0145 narrative.',REPORT+' · PDF pp. 15–16 / printed pp. 7–8: collision and subsequent actions.',REPORT+' · PDF p. 52 / printed p. 44: investigation conclusions.',WEEK+' · pp. 25–45: evidence, precise location, source/value/unit and cautious reporting.'],aiRole:'Evidence reviewer / traffic-information recipient',aiPurpose:'Question overclaims, rehearse a traffic clarification and help distinguish contemporaneous information from later findings.',documents:[
doc('case-map','Case orientation','MAIB 29/2014 · PDF p. 14 / printed p. 6','Date: 11 January 2014. Area: south-west lane, Dover Strait Traffic Separation Scheme. Rickmers Dubai was on passage Hamburg–Genoa. Tug Kingston and unmanned crane barge Walcon Wizard were on passage Ipswich–Southampton. This description identifies vessels and routes; it does not establish fault.'),
doc('cnis-0115','0115 UTC · CNIS narrative data','MAIB 29/2014 · PDF p. 14 / printed p. 6, Figure 1 and narrative','Rickmers Dubai: COG 233°, SOG 15.4 knots. Kingston directly ahead at range 6.3 NM: COG 237°, speed 6 knots. Wire towline length: 250 m. Predicted CPA between ship and tug: about 250 m at 0155. Weather: south-westerly Beaufort 5–6, moderate to rough sea, good visibility. These are historical reported values, not live sensor readings.'),
doc('cnis-0145','0145 UTC · Closing distance','MAIB 29/2014 · PDF pp. 14–15 / printed pp. 6–7, Figure 2 and narrative','Reported distance between Rickmers Dubai and Kingston: 1.6 NM. Reported CPA between the two vessels: 40 m. Kingston’s watchkeeper assessed that the cargo ship would pass clear on the starboard side of tug and tow. His assessment is not proof that a safe passing agreement existed.',1),
doc('source-limit','Radar / AIS source limitations','MAIB 29/2014 · PDF pp. 35–36 / printed pp. 27–28; paraphrase','AIS information is an additional source, not a complete representation of all traffic. Absence of an AIS transmission is not evidence that no vessel or tow exists. Radar observations and visual correlation remain distinct evidence. In this exercise, no verified bearing is supplied for the 0145 data: do not copy an illustrative 045° bearing from a classroom example.',2),
doc('tow','Tug-and-tow information','MAIB 29/2014 · PDF p. 14 / printed p. 6','Kingston was towing Walcon Wizard on a 250 m wire. Treat tug and tow as related but distinct objects when describing position and hazards. A CPA stated for the tug is not automatically a clearance value for the barge or towline.',2),
doc('traffic-draft','Draft message to repair','Fictional trainee draft, NOT a historical VHF quotation','“There is no AIS target, so the way is clear. That dangerous ship will definitely collide. Turn now.” Task: separate source data, uncertainty, traffic-information function and a request for intentions. You are practising communication, not issuing a navigation instruction.',3),
doc('events','0154–0159 UTC · Reported events','MAIB 29/2014 · PDF pp. 15–16 / printed pp. 7–8','At 0154 Rickmers Dubai altered to port to overtake Kingston and collided with Walcon Wizard seconds later. The ship passed between barge and tug, catching the towline. At 0155 Kingston’s watchkeeper broadcast a warning on VHF channel 16. At 0159 he reported the collision and loss of tow to Dover Coastguard and reported his crew uninjured. This packet is released only after your pre-collision traffic message.',4),
doc('findings','Investigation findings · later evidence','MAIB 29/2014 · PDF p. 52 / printed p. 44, §3.1','The report found that the OOW had not kept a proper lookout, did not see Walcon Wizard or recognise the towing operation, and was alone on the bridge. It described over-reliance on AIS/ECDIS as the almost certain explanation for the late detection. Radar targets had been present for almost an hour; they were not acquired using ARPA. Neither tug nor barge was transmitting AIS. These are attributed findings from the later investigation, not facts derivable from a photograph alone.',6)
],stages:[
task('orientation','01 / Establish what each source can show','0115 UTC','Identify the entities, reference frame and limits before describing the encounter.',['case-map','cnis-0115'],[
pick('tow-identity','Which vessel was the unmanned crane barge?',['Walcon Wizard','Kingston','Rickmers Dubai'],'Walcon Wizard'),pick('frame','What is the reference for “directly ahead” in the 0115 account?',['Rickmers Dubai','A person facing the chart','The port entrance'],'Rickmers Dubai'),text('opening-facts','Two sourced facts and one claim you cannot make from this packet',120)],{aiRole:'Evidence reviewer',aiTask:'Check that the learner separates entity identification from blame. Only the orientation and 0115 packet are available; do not reveal later collision events or conclusions.',delivery:'Evidence notebook · opening observations',consequence:'Vessel identities and reference frame are fixed. A later traffic sample is now released.'}),
task('compare','02 / Compare two traffic samples','0145 UTC','Use the two dated packets to report change without mixing range, CPA or units.',['cnis-0115','cnis-0145'],[
pick('range','Range at 0145',['1.6 NM','6.3 NM','40 NM'],'1.6 NM'),pick('cpa','Reported CPA at 0145',['40 m','250 NM','1.6 m'],'40 m'),pick('trend','Supported comparison',['Range and reported CPA decreased','A safe passing agreement was confirmed','Visibility caused the encounter'],'Range and reported CPA decreased'),text('data-report','Three data sentences: source/time, value/unit, and cautious implication',160)],{visual:'traffic',aiRole:'Traffic-information recipient',aiTask:'Ask for clarification only if the learner confuses the timestamp, source, range or CPA. Explain the difference when asked. Do not invent a bearing.',delivery:'Communication watch · traffic update',consequence:'Your update identifies a developing proximity concern; absence of an AIS label now needs to be interpreted.'}),
task('source-check','03 / Resolve the missing AIS label','0145 UTC · evidence check','Choose the supported interpretation and document what still needs verification.',['source-limit','tow','cnis-0145'],[
pick('ais','No AIS identity means…',['Traffic may still exist; correlate other sources','The contact is not real','The tow is safely clear'],'Traffic may still exist; correlate other sources'),pick('geometry','The 40 m CPA is…',['A reported value between ship and tug, not proven towline clearance','A verified safe distance from the barge','The length of the towline'],'A reported value between ship and tug, not proven towline clearance'),text('verification-plan','Name two sources/checks and the specific uncertainty each would address',150)],{aiRole:'Evidence reviewer',aiTask:'Challenge the assumption that no AIS label means no contact. Discuss the scope of a tug CPA without giving a manoeuvring order. Use the current packets only.',delivery:'Evidence notebook · verification plan',consequence:'The absence of AIS is recorded as a source limitation. A trainee traffic message is available for repair.'}),
task('radio','04 / Repair and transmit the traffic message','Training reconstruction · before outcome release','Write a precise traffic-information exchange. Use historical values; do not manufacture the missing bearing.',['traffic-draft','cnis-0145','tow'],[
pick('function','Message function',['Traffic information and request for intentions','Unqualified prediction of collision','Departure permission'],'Traffic information and request for intentions'),text('traffic-message','Your traffic message: function, identified contact/reference, verified range/time and uncertainty',150),text('clarification','Recipient’s clarification and your readback: preserve the unknown bearing explicitly',100)],{aiRole:'Traffic-information recipient',aiTask:'Act as the receiver of the drafted traffic message. Check target identity, time and units. A bearing was not supplied; request verification instead of inventing one. Your reply is a rehearsal, not a historical transcript.',delivery:'Traffic-information channel · reconstructed exchange',consequence:'Your pre-outcome message is preserved. The historical event packet is released next; it cannot be rewritten as a prevented collision.'}),
task('chronology','05 / Reconstruct the reported sequence','0154–0159 UTC','Order the events and write a short past-tense account without turning chronology into an unsupported causal claim.',['events'],[
pick('event1','First event',['0154 alteration and collision with Walcon Wizard','0159 report to Coastguard','0155 VHF warning'],'0154 alteration and collision with Walcon Wizard'),pick('event2','Next dated event',['0155 VHF warning','0159 report to Coastguard','0115 collision'],'0155 VHF warning'),pick('event3','Later report',['0159 report to Coastguard','0145 completed investigation','0154 permission to pass'],'0159 report to Coastguard'),text('chronology-note','Four chronological sentences with vessel names, times and specific incident verbs',180)],{aiRole:'Incident recorder',aiTask:'Help the learner order the reported sequence using past tense. Do not imply the training message changed the historical outcome or supply a legal determination.',delivery:'Incident desk · chronology',consequence:'The chronology is anchored to the report. You will now identify and repair overclaims in an incident summary.'}),
task('claims','06 / Audit claims before publication','Evidence review','Distinguish an observed value, someone’s assessment and an unsupported conclusion.',['cnis-0145','source-limit','events'],[
pick('claim1','“The tug watchkeeper expected a clear pass.”',['Attributed assessment','Proven safe passing agreement'],'Attributed assessment'),pick('claim2','“No AIS target means no vessel.”',['Unsupported conclusion','Checked fact'],'Unsupported conclusion'),pick('claim3','“The cargo ship collided with the barge at 0154.”',['Reported event','A conclusion from a classroom photograph'],'Reported event'),text('repair-claim','Repair two of the weak claims and state the source or missing evidence for each',190)],{aiRole:'Critical reviewer',aiTask:'Challenge the evidential strength of the learner’s wording. Ask what source supports a claim, but answer specific questions directly. Later investigation findings are not yet released.',delivery:'Editorial review · claim audit',consequence:'Unsupported certainty is removed from the draft. Later investigation findings can now be compared with your provisional account.'}),
task('findings-review','07 / Attribute the investigation findings','After the event · MAIB findings','Compare what your early packets supported with what the later investigation established.',['findings','cnis-0145'],[
pick('attribution','Best attribution',['The MAIB investigation found…','The 0145 screen proves every cause…','The photograph establishes legal blame…'],'The MAIB investigation found…'),text('comparison','Identify one later finding, one earlier uncertainty, and why the evidence status differs',200)],{aiRole:'Investigation reviewer',aiTask:'Support accurate attribution to MAIB and distinction between contemporary observations and later analysis. Do not apportion legal blame. Discuss the almost-certain wording as attributed confidence, not absolute proof.',delivery:'Investigation notebook · hindsight comparison',consequence:'Your final note can report the investigation’s conclusions with explicit attribution and a clear evidence boundary.'}),
task('report','08 / Produce the evidence-led incident note','Final review','Write a professional account that another reader can trace back to the released documents.',['case-map','events','findings'],[
text('final-report','Incident evidence note · suggested 250–350 words',800,'Separate dated facts, attributed assessments, later findings and communication lessons. Cite source IDs or report sections.'),text('reflection','Debrief: identify one claim you weakened or strengthened after seeing another source',130)],{aiRole:'Maritime English reviewer',aiTask:'Review the student’s note for attribution, chronology, technical precision and overclaiming. Offer targeted edits and reasons without producing the assessed note.',delivery:'Instructor · evidence-led incident note',final:true,consequence:'The packet preserves your pre-outcome message, chronology, claim audit and later interpretation separately.'})]},
m4:{id:'m4',number:'04',title:'Evidence Before Clearance',subtitle:'A corrective action needs proof of closure.',kind:'Inspection control room',duration:'60–80 min',role:'Chief Officer’s documentation coordinator',ship:'MV Meridian · cargo deck / deck 3',clock:'15:45–16:35 UTC',intro:'An inspection handover includes an imprecise fire-door report, loose lashings and conflicting cargo records. Locate each finding, write actionable tickets, review rectification evidence and prepare an honest status report before the planned departure.',basis:'Fictional inspection exercise grounded in WEEK 2–3 pp. 46–55 and the evidence/claim distinctions in pp. 25–43. It is not a reconstruction of Hoegh Osaka or a formal PSC decision. The linked course case informs the language, not invented historical findings.',sourceNotes:[WEEK+' · pp. 28–31: precise ship-relative location.',WEEK+' · pp. 46–53: cargo/stability terminology and incident sequence.',WEEK+' · pp. 54–55: item, evidence, risk, corrective action and record.',WEEK+' · pp. 17–22: prerequisites, actor and verification.'],aiRole:'Inspector / verification reviewer',aiPurpose:'Rehearse inspection questions, expose unsupported closure claims and review a corrective-action ticket against the documented evidence.',documents:[
doc('handover','15:45 · Inspection handover','Fictional scenario record','Vessel MV Meridian. Planned departure 1700 UTC. Finding D-01: “door at the back does not work.” Finding D-02: loose lashings seen near No. 2 hatch, starboard side. Finding D-03: cargo record revision A and loading summary revision B do not match. The handover does not prove an unsafe stability condition or an official detention.'),
doc('plan','Deck reference plan','Original schematic for this exercise; not a navigational or structural plan','Bow is at the top. Port is left when looking forward. No. 2 hatch is forward of the accommodation block. Fire door FD-3A is on deck 3, port side, aft of the accommodation access corridor. Location labels are scenario references. The schematic is not to scale.'),
doc('door','D-01 · Observed fire-door test',WEEK+' · p. 55; fictional inspection evidence','Item: FD-3A, deck 3 port side, aft of accommodation access corridor. Test at 1548: after release from the fully open position, the door did not close fully. No smoke or fire observed. Possible implication: fire integrity may be affected. The evidence does not establish that a fire occurred.'),
doc('cargo','D-03 · Conflicting cargo records','Fictional document extracts','Cargo manifest revision A: 84 cargo units. Loading summary revision B: 86 cargo units. Revision B has no verification signature. No approved corrected calculation is supplied. Do not calculate stability from the count alone or claim that cargo shifted. Refer the discrepancy to the responsible loading officer.',2),
doc('lashings','D-02 · Deck check','Fictional observation based on WEEK 2–3 p. 22','Loose lashings observed near No. 2 hatch on the starboard side at 1545. Rain began at 1530. One AB available. Departure planned for 1700. No measured cargo movement is recorded. The scenario requires the work to be reported and then checked by the OOW.',2),
doc('tickets','Company follow-up procedure','Fictional procedure supplied for this exercise','Each record must identify the item/location; the observation and source; a cautiously phrased risk; a named responsible role and deadline; and independent verification before closure. The coordinator records evidence and recommends status. Formal clearance or detention is outside the coordinator’s authority.',3),
doc('returns','16:10 · Rectification returns','Fictional maintenance and operations replies','D-01 engineer: “Closer adjusted; door looks fine.” No repeat-test record supplied. D-02 AB: “Lashings secured 1600”; OOW signs verification at 1605. D-03 loading officer: corrected manifest revision C and loading summary C agree on 86 units; verification signature still pending.',4),
doc('retest','16:22 · Fire-door repeat test','Fictional verification record','FD-3A tested by duty engineer and witnessed by Chief Officer at 1622: three complete closing cycles recorded, door closed fully on each cycle. Adjustment and test entered in maintenance log ML-42. This closes the scenario’s D-01 verification requirement; it is not an official PSC clearance.',5),
doc('final-packet','16:30 · Last document return','Fictional evidence packet','D-01: witnessed repeat test and ML-42 recorded. D-02: OOW verification signed. D-03: revision C records agree, but the loading officer has not provided the required signed verification. No Master authorisation is recorded. The deadline does not transform the missing signature into evidence.',6)
],stages:[
task('locate','01 / Make the finding locatable','15:45 UTC','Use the schematic and the test record to replace an ambiguous location.',['handover','plan','door'],[
{id:'location',type:'map',label:'Locate FD-3A on the schematic',expected:'port-aft'},text('location-message','Repair “the door at the back”: give deck, side, reference point, item ID and observed behaviour',140)],{visual:'deck',aiRole:'Inspecting officer',aiTask:'Act as a colleague who must locate the item without gestures. Check precise ship-relative terms, not generic front/back. Do not invent another deck or door.',delivery:'Inspection team · location repair',consequence:'The location is identifiable. Your next task is to separate observed failure from possible risk.'}),
task('classify','02 / Separate observation, risk and allegation','15:48 UTC','The door failed its test. Decide what can be recorded and what cannot be claimed.',['door','handover'],[
pick('observed','Observed evidence',['Door failed to close fully during the test','A fire occurred','The vessel has been detained'],'Door failed to close fully during the test'),pick('risk','Defensible risk statement',['Fire integrity may be affected','Fire spread has been proved','Stability is necessarily insufficient'],'Fire integrity may be affected'),text('evidence-note','Write an observation sentence and a separate risk sentence, each tied to D-01',110)],{aiRole:'Inspector',aiTask:'Review the observation/risk separation. Explain may affect versus caused. Do not turn the fictional exercise into a legal detention determination.',delivery:'Inspection notebook · D-01 evidence',consequence:'The finding has a specific observed condition. Two other records now require a different type of evidence check.'}),
task('reconcile','03 / Reconcile records without inventing stability','15:55 UTC','Read the cargo discrepancy and the lashing observation as two different findings.',['cargo','lashings'],[
pick('count','Document discrepancy',['84 units in A versus 86 in B','Both documents verified at 84','Cargo shift established by the counts'],'84 units in A versus 86 in B'),pick('cargo-action','Required response',['Request reconciled verified records from the loading officer','Invent a corrected stability value','Declare the ship stable because counts differ by only two'],'Request reconciled verified records from the loading officer'),text('cargo-query','To loading officer: identify both versions, exact discrepancy and verification requested',150),text('lashing-order','To AB: specify location, task, before-departure deadline and report-back/OOW check',130)],{aiRole:'Loading officer',aiTask:'Answer questions about the two supplied versions; do not invent weights, draught, GM or a stability calculation. Help the learner request the missing verification clearly.',delivery:'Loading officer + AB · separate communications',consequence:'Document correction and physical securing are separate work streams. Both need an owner and evidence of closure.'}),
task('ticket','04 / Issue the corrective-action ticket','16:00 UTC','Build a ticket another person can carry out and another person can verify.',['door','tickets'],[
text('ticket-item','Item and exact location',60),text('ticket-evidence','Observed evidence, time and source',85),text('ticket-risk','Risk phrased at the strength supported by the observation',65),text('ticket-action','Responsible role, corrective action and deadline',100),text('ticket-proof','What record/test and witness will be needed before closing D-01?',100)],{aiRole:'Inspecting officer',aiTask:'Review the drafted ticket field by field. Point to a specific missing or vague element and explain why it matters. Do not automatically approve or complete the ticket.',delivery:'Duty engineer · D-01 action ticket',consequence:'The ticket has been issued. An engineer’s reassuring reply is not yet the verification record.'}),
task('returns-review','05 / Audit rectification replies','16:10 UTC','Classify the returns. Close only what has the required verification.',['returns','tickets'],[
pick('d1','D-01 status',['Adjusted; repeat-test evidence pending','Verified closed'],'Adjusted; repeat-test evidence pending'),pick('d2','D-02 status',['Verified in this scenario','No reply received'],'Verified in this scenario'),pick('d3','D-03 status',['Records reconciled; signed verification pending','All controls verified'],'Records reconciled; signed verification pending'),text('challenge','To duty engineer: challenge “looks fine” and specify the repeat-test evidence needed',140)],{aiRole:'Duty engineer',aiTask:'Rehearse an evidence-focused follow-up to “looks fine”. Explain the difference between reported work and witnessed verification. Do not invent test results before the retest packet is released.',delivery:'Duty engineer · verification request',consequence:'A repeat test is requested for D-01. D-03 remains an independent open item.'}),
task('retest-check','06 / Accept evidence within its scope','16:22 UTC','Check whether the repeat-test packet answers your request without allowing one closure to close every finding.',['retest','returns'],[
pick('test-status','What does the repeat test establish?',['D-01 verification requirement met in this exercise','Every ship deficiency is closed','Departure is authorised'],'D-01 verification requirement met in this exercise'),text('closure-entry','D-01 closure entry: result, witness, time, maintenance reference and scope',150),text('remaining','Name the remaining document control and the evidence still required',100)],{aiRole:'Verification reviewer',aiTask:'Check that closure cites ML-42, the repeat test and its scope. Ask the student to distinguish D-01 closure from D-03’s missing signature only if omitted.',delivery:'Maintenance record · D-01 closure',consequence:'D-01 can be recorded as verified for the exercise. Departure readiness still depends on the remaining document trail.'}),
task('hold','07 / Report the unresolved condition','16:30 UTC','Time pressure does not replace evidence. Select a defensible recommendation and brief the Master.',['final-packet','tickets'],[
pick('recommendation','Your recommendation',['Keep D-03 open and report missing verification to Master','Declare all checks complete to meet the schedule','Issue an official detention order'],'Keep D-03 open and report missing verification to Master'),text('master-brief','Four-sentence status briefing: verified items; open item; consequence/limit; requested action',230)],{aiRole:'Master',aiTask:'Challenge an unsupported “all clear”. Ask for a precise outstanding control and the person responsible. Do not give actual departure permission or make legal decisions.',delivery:'Master · readiness exception briefing',consequence:'The readiness record preserves D-03 as open; the final packet must not erase it because other work was completed.'}),
task('submission','08 / Submit the corrective-action dossier','16:35 UTC','Write a concise record that separates findings, actions, proof and remaining uncertainty.',['door','cargo','retest','final-packet'],[
text('final-report','Inspection follow-up report · suggested 250–350 words',800,'Use item/evidence/risk/action/verification structure. Preserve the missing verification and avoid claiming a real PSC detention.'),text('reflection','Debrief: explain one change from vague language to verifiable language, citing your ticket',140)],{aiRole:'Inspection report reviewer',aiTask:'Review the student’s report against the released packet. Offer precise comments on evidence and wording, not a completed report or a language score.',delivery:'Instructor · corrective-action dossier',final:true,consequence:'The dossier records two verified controls and one honestly unresolved verification, rather than an artificial all-clear.'})]}
};
if(typeof module!=='undefined'&&module.exports)module.exports=missions;else root.OperationsMissions=missions;
})(globalThis);
